### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by ProfessorGinno** [ProfessorGinno/recipe-blog#5]
- [x] Correcta distribución de las carpetas 
- [ ] información bien documentada -> Todos
- [x] Aplicar las buenas prácticas vistas en cada módulo.
- [x] Usar entornos virtuales (opcional).
- [x] Crear el archivo requirements.txt con las tecnologías y respectiva versión usada para el proyecto.
- [x] Que se tenga siquiera un commit de cada integrante del grupo.
- [x] Todo esté subido a la rama main.
- [ ] Se deben aplicar la función de búsqueda por título las publicaciones y fecha -> Juan
- [x] Crear un blog que cumpla con la sección de usuarios
- [ ] Repostear -> Ginno
- [x] autenticación
- [x] publicaciones que puedan tener la opción de recibir comentarios -> Ginno
- [x] Atualization date -> Ginno
- [ ] Dificultad -> Ginno
- [x] en el modelo de usuario tener el campo de país y que a la hora de ser llenado, se llene en tiempo real con la api de https://restcountries.com/
- [ ] se podría guardar en un cache de redis que dure 1 hora (opcional)
- [ ] la app debe contener test unitarios -> Ginno - Mar - Juan
- [ ] para la parte de análisis que permita mostrar las iteraciones con el blog, usando Pandas y Matplotlib para las gráficas. -> Mar
- [x] Utilización de códigos de respuesta http, los verbos y la estructura de rest
- [ ] Aplicar el modelo de APIS -> Juan
- [ ] Utilizar celery y redis -> Todos
- [ ] Actualizar el requirements.txt con requests -> Ginno
